### PR TITLE
Fix missing API serix tags

### LINKED ISSUE #666: Fix serix tags for web API
We use serix to serialize the web api responses, but there are several length tags missing it seems.

### PR DESCRIPTION
**Pull request by muXxer**

### CODE REVIEW

File: api/management.go [hunk 1]
```diff
@@ -8,25 +8,25 @@ type (
 	// AddPeerRequest defines the request for a POST peer REST API call.
 	AddPeerRequest struct {
 		// The libp2p multi address of the peer.
-		MultiAddress string `serix:""`
+		MultiAddress string `serix:",lenPrefix=uint8"`
 		// The alias of to identify the peer.
-		Alias string `serix:",omitempty"`
+		Alias string `serix:",lenPrefix=uint8,omitempty"`
```
Comment (PhilippGackstatter) [inline api/management.go:13]: The comment above this line needs a fix.

File: api/management_test.go [hunk 2]
```diff
@@ -1,68 +1,323 @@
...
+			Source: &api.CreateSnapshotsRequest{
+				Slot: 1,
+			},
+			Target: `{
+	"slot": 1
+}`,
+		},
+		{
+			Name: "ok - CreateSnapshotsResponse",
+			Source: &api.CreateSnapshotsResponse{
```
Comment (PhilippGackstatter) [inline api/management_test.go]: Should this really be `CreateSnapshotsResponse` and not `CreateSnapshotResponse`?

**Review by PhilippGackstatter — APPROVED** [review]
